### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by vsoch** [VClinic/VClinic#1]
Hi! Is this tool still maintained? I noticed the build.sh doesn't work and it requires Python 2 (which is deprecated for a bit). Here is the build error:

```
init env...
Linking source files and cmakefiles..
make...
Prepare build directory and log directory ..
Enter /tmp/VClinic/scripts/build_tool/../../build ..
Running Cmake .. (See /tmp/VClinic/scripts/build_tool/../../logs/cmake.log.1702272584 for detail)
 Cmake fail! 
fix build error 9
Traceback (most recent call last):
  File "/tmp/VClinic/scripts/build_tool/temp_solution/flags_make_autofix.py", line 13, in <module>
    with open(filePath, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/VClinic/scripts/build_tool/../../build/ext/drwrap/CMakeFiles/drwrap.dir/flags.make'
Traceback (most recent call last):
  File "/tmp/VClinic/scripts/build_tool/temp_solution/flags_make_autofix.py", line 13, in <module>
    with open(filePath, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/VClinic/scripts/build_tool/../../build/core/CMakeFiles/dynamorio.dir/flags.make'
Traceback (most recent call last):
  File "/tmp/VClinic/scripts/build_tool/temp_solution/flags_make_autofix.py", line 13, in <module>
    with open(filePath, "r+") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/VClinic/scripts/build_tool/../../build/core/CMakeFiles/dynamorio_static.dir/flags.make'
Running make .. (See /tmp/VClinic/scripts/build_tool/../../logs/make.log.1702272584 for detail)
 Make fail! 
```
Could the Dockerfile be added to the repository? Thanks!

**Comment by JerryYouxin** [comment]
Sorry for my late reply. The build scripts is still work for Ubuntu 20.02 and python2 can be installed with `apt-get install python2`. Can you provide the detailed system configuration? Is this script still not work when python2 is installed?

**Comment by vsoch** [comment]
I think likely we don't want to rely on Python 2.

**Comment by JerryYouxin** [comment]
> init env...
> Linking source files and cmakefiles..
> make...
> Prepare build directory and log directory ..
> Enter /tmp/VClinic/scripts/build_tool/../../build ..
> Running Cmake .. (See /tmp/VClinic/scripts/build_tool/../../logs/cmake.log.1702272584 for detail)
>  Cmake fail! 
> fix build error 9

Actually, the build script should not rely on python2. Only the test script uses python2. Could you provide the content of cmake log file '/tmp/VClinic/scripts/build_tool/../../logs/cmake.log.1702272584'? It seems that the cmake fails within building process.

**Comment by vsoch** [comment]
Here you go...
```
cat /tmp/VClinic/scripts/build_tool/../../logs/make.log.1703275236
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by JerryYouxin** [comment]
Thank you for replying. The provided log of make seems that the previous cmake stage fails and the Makefile is not generated correctly. Can you provide the cmake log?

> Could you provide the content of cmake log file '/tmp/VClinic/scripts/build_tool/../../logs/cmake.log.1702272584'? It seems that the cmake fails within building process.

**Comment by vsoch** [comment]
Ack sorry - just copy pasted the one shown in the terminal! Here you go:

```console
$ cat logs/cmake.log.1703275236 
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for x86
-- Version number: 8.0.18936
-- Performing Test proc_found_avx
-- Performing Test proc_found_avx - Success
-- Compiler and processor support AVX.
-- Performing Test proc_found_avx2
-- Performing Test proc_found_avx2 - Success
-- Compiler and processor support AVX2.
-- Performing Test proc_found_avx512
-- Performing Test proc_found_avx512 - Failed
-- WARNING: Compiler or processor do not support AVX-512. Skipping tests
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/as
-- Found Perl: /usr/bin/perl (found version "5.34.0") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of uint
-- Check size of uint - done
-- Check size of ushort
-- Check size of ushort - done
-- Check size of bool
-- Check size of bool - failed
-- Check size of byte
-- Check size of byte - failed
-- Check size of sbyte
-- Check size of sbyte - failed
-- Check size of uint32
-- Check size of uint32 - failed
-- Check size of uint64
-- Check size of uint64 - failed
-- Check size of int32
-- Check size of int32 - failed
-- Check size of int64
-- Check size of int64 - failed
-- Check size of _Bool
-- Check size of _Bool - done
-- Performing Test cxx17_available
-- Performing Test cxx17_available - Success
-- Performing Test no_stack_protector_avail
-- Performing Test no_stack_protector_avail - Success
-- Performing Test suggest_override_avail
-- Performing Test suggest_override_avail - Success
-- Performing Test nounused_avail
-- Performing Test nounused_avail - Success
-- Performing Test stringop_truncation_avail
-- Performing Test stringop_truncation_avail - Success
-- Performing Test format_truncation_avail
-- Performing Test format_truncation_avail - Success
-- Performing Test stringop_overflow_avail
-- Performing Test stringop_overflow_avail - Success
-- Performing Test HAVE_TYPELIMITS_CONTROL
-- Performing Test HAVE_TYPELIMITS_CONTROL - Success
-- Performing Test HAVE_FVISIBILITY_INTERNAL
-- Performing Test HAVE_FVISIBILITY_INTERNAL - Success
-- Performing Test HAVE_FVISIBILITY_HIDDEN
-- Performing Test HAVE_FVISIBILITY_HIDDEN - Success
-- Looking for linux/rseq.h
-- Looking for linux/rseq.h - found
-- Looking for libunwind.h
-- Looking for libunwind.h - not found
-- Performing Test no_pie_avail
-- Performing Test no_pie_avail - Success
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")  
CMake Deprecation Warning at clients/deadspy/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/deadspy_naive/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Performing Test implicit_fallthrough_avail
-- Performing Test implicit_fallthrough_avail - Success
CMake Deprecation Warning at clients/loadspy/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/loadspy_naive/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/mul_followed_by_div/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/redspy/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/redspy_naive/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/trivialspy/CMakeLists.txt:7 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_all_opnd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_all_opnd_sd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_mem_and_reg/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_mem_and_reg_read/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_mem_and_reg_read_sd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_mem_and_reg_sd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_memory/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_memory_read/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_memory_read_sd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_memory_sd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vprofile_print_value/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vtrace_all_opnd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/vtrace_instrs_first_opnd/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/zerospy/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/zerospy_data_centric/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at clients/zerospy_naive/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- WARNING: vera++ not found: disabling code style checks
CMake Error at /home/vanessa/anaconda3/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "GL/gl.h" in
  "/home/vanessa/anaconda3/include;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/libdrm;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include".
Call Stack (most recent call first):
  /home/vanessa/anaconda3/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:233 (include)
  /home/vanessa/anaconda3/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:100 (find_package)
  ext/drgui/CMakeLists.txt:39 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by JerryYouxin** [comment]
> CMake Deprecation Warning at clients/trivialspy/CMakeLists.txt:7 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.

It seems that your cmake version is too low. I recommend to use cmake 3 for better compatibility.

> CMake Error at /home/vanessa/anaconda3/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
>   Failed to find "GL/gl.h" in
>   "/home/vanessa/anaconda3/include;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/libdrm;/opt/conda/conda-bld/qt-main_1660123285207/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include".
> Call Stack (most recent call first):
>   /home/vanessa/anaconda3/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:233 (include)
>   /home/vanessa/anaconda3/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:100 (find_package)
>   ext/drgui/CMakeLists.txt:39 (find_package)

The cmake error seems that the cmake detects there exists Qt in the system, but the opengl library is not properly configured (or missed in this system) to build the drgui extention within dynamorio. As dynamorio can disable the configuration and build of drgui when there is no Qt detected in the system, you can either choose to use a system without Qt installation or try to install the GL library to pass the drgui configuration.
